"""Schemas for the agreement endpoints (BUILD_SPEC Phase 8).

The create schema validates the client-supplied investment terms; server-owned
fields (``agreement_number``, ``qr_code_token``, ``pdf_path``, ``status``) are
generated by the service and never accepted from the client. Response schemas
never expose the internal ``pdf_path``.
"""

from marshmallow import EXCLUDE, RAISE, Schema, fields, validate

from ..models import AgreementStatus


class AgreementCreateSchema(Schema):
    """Validates ``POST /agreements/generate``."""

    class Meta:
        unknown = RAISE

    customer_id = fields.Integer(required=True)
    investment_amount = fields.Decimal(
        required=True, as_string=True, validate=validate.Range(min=0, min_inclusive=False)
    )
    duration_months = fields.Integer(
        required=True, validate=validate.Range(min=1, max=600)
    )
    interest_rate = fields.Float(
        required=True, validate=validate.Range(min=0, max=100)
    )


class _CustomerSummarySchema(Schema):
    id = fields.Integer(dump_only=True)
    customer_code = fields.String(dump_only=True)
    full_name = fields.String(dump_only=True)


class AgreementResponseSchema(Schema):
    """Representation of a generated agreement (no internal file path)."""

    class Meta:
        unknown = EXCLUDE

    id = fields.Integer(dump_only=True)
    customer_id = fields.Integer(dump_only=True)
    created_by = fields.Integer(dump_only=True)
    agreement_number = fields.String(dump_only=True)
    investment_amount = fields.Decimal(dump_only=True, as_string=True)
    duration_months = fields.Integer(dump_only=True)
    interest_rate = fields.Float(dump_only=True)
    qr_code_token = fields.String(dump_only=True, allow_none=True)
    status = fields.Enum(AgreementStatus, by_value=True, dump_only=True)
    signed_at = fields.DateTime(dump_only=True, allow_none=True)
    has_pdf = fields.Function(lambda a: a.pdf_path is not None, dump_only=True)


class AgreementDetailSchema(AgreementResponseSchema):
    """Detail view: adds the customer summary."""

    customer = fields.Nested(_CustomerSummarySchema, dump_only=True)


# Singletons for reuse in routes.
agreement_create_schema = AgreementCreateSchema()
agreement_response_schema = AgreementResponseSchema()
agreements_response_schema = AgreementResponseSchema(many=True)
agreement_detail_schema = AgreementDetailSchema()
