"""Schemas for customer create / update / response payloads.

Input schemas reject unknown fields (BUILD_SPEC section 3, rule 4). Server-owned
fields (``id``, ``customer_code``, ``registered_at``, ``is_deleted``) are never
accepted from the client — ``customer_code`` is generated by the service and
``status`` defaults to ``pending`` on creation.
"""

from marshmallow import EXCLUDE, RAISE, Schema, fields, validate

from ..models import CustomerStatus, DocType, ProposalWorkflowStatus, VerificationStatus

# Reused validators.
_nic = validate.Length(min=1, max=20)
_full_name = validate.Length(min=1, max=150)


class CustomerCreateSchema(Schema):
    """Validates ``POST /customers``."""

    class Meta:
        unknown = RAISE

    nic_number = fields.String(required=True, validate=_nic)
    full_name = fields.String(required=True, validate=_full_name)
    address = fields.String(required=False, allow_none=True, validate=validate.Length(max=250))
    phone = fields.String(required=False, allow_none=True, validate=validate.Length(max=20))
    email = fields.Email(required=False, allow_none=True, validate=validate.Length(max=150))
    # Optional: admins/head-office staff may assign a rep. For a sales_rep this
    # is ignored and forced to their own id by the service.
    assigned_rep_id = fields.Integer(required=False)


class CustomerUpdateSchema(Schema):
    """Validates ``PUT /customers/{id}``. All fields optional (partial update)."""

    class Meta:
        unknown = RAISE

    nic_number = fields.String(validate=_nic)
    full_name = fields.String(validate=_full_name)
    address = fields.String(allow_none=True, validate=validate.Length(max=250))
    phone = fields.String(allow_none=True, validate=validate.Length(max=20))
    email = fields.Email(allow_none=True, validate=validate.Length(max=150))
    status = fields.Enum(CustomerStatus, by_value=True)
    assigned_rep_id = fields.Integer()


class _RepSummarySchema(Schema):
    """Minimal representation of the assigned sales rep."""

    id = fields.Integer(dump_only=True)
    full_name = fields.String(dump_only=True)
    email = fields.Email(dump_only=True)
    role = fields.Function(lambda user: user.role.value, dump_only=True)


class CustomerResponseSchema(Schema):
    """List/summary representation of a customer."""

    class Meta:
        unknown = EXCLUDE

    id = fields.Integer(dump_only=True)
    customer_code = fields.String(dump_only=True)
    nic_number = fields.String(dump_only=True)
    full_name = fields.String(dump_only=True)
    address = fields.String(dump_only=True, allow_none=True)
    phone = fields.String(dump_only=True, allow_none=True)
    email = fields.Email(dump_only=True, allow_none=True)
    assigned_rep_id = fields.Integer(dump_only=True)
    status = fields.Enum(CustomerStatus, by_value=True, dump_only=True)
    registered_at = fields.DateTime(dump_only=True)


class _DocumentSummarySchema(Schema):
    id = fields.Integer(dump_only=True)
    doc_type = fields.Enum(DocType, by_value=True, dump_only=True)
    verification_status = fields.Enum(VerificationStatus, by_value=True, dump_only=True)
    uploaded_at = fields.DateTime(dump_only=True)


class _ProposalSummarySchema(Schema):
    id = fields.Integer(dump_only=True)
    product_type = fields.String(dump_only=True, allow_none=True)
    workflow_status = fields.Enum(ProposalWorkflowStatus, by_value=True, dump_only=True)
    submitted_at = fields.DateTime(dump_only=True)


class CustomerDetailSchema(CustomerResponseSchema):
    """Detail representation: the customer plus rep, documents, and proposals."""

    assigned_rep = fields.Nested(_RepSummarySchema, dump_only=True)
    documents = fields.List(fields.Nested(_DocumentSummarySchema), dump_only=True)
    proposals = fields.List(fields.Nested(_ProposalSummarySchema), dump_only=True)


# Singletons for reuse in routes.
customer_create_schema = CustomerCreateSchema()
customer_update_schema = CustomerUpdateSchema()
customer_response_schema = CustomerResponseSchema()
customer_detail_schema = CustomerDetailSchema()
customers_response_schema = CustomerResponseSchema(many=True)
