"""Schemas for product create / update / response payloads.

Input schemas reject unknown fields (BUILD_SPEC section 3, rule 4). Server-owned
fields (``id``, ``product_code``, ``is_deleted``, ``created_at``, ``updated_at``)
are never accepted from the client — ``product_code`` is generated by the service
and ``is_deleted`` only ever changes through ``DELETE /products/{id}``.

Amounts are carried as strings (like ``Proposal.proposed_amount``) so decimal
precision survives the JSON round-trip.
"""

from marshmallow import (
    EXCLUDE,
    RAISE,
    Schema,
    ValidationError,
    fields,
    validate,
    validates_schema,
)

from ..models import ProductCategory

# Reused validators.
_name = validate.Length(min=1, max=150)
_positive_amount = validate.Range(min=0, min_inclusive=False)
_positive_months = validate.Range(min=1)
_non_negative_rate = validate.Range(min=0)


def _check_amount_window(data: dict) -> None:
    """Reject ``max_investment`` below ``min_investment`` when both are present.

    Only meaningful when the payload carries both. A partial update that supplies
    just one of the two is re-checked against the stored row in
    ``product_service.update_product``.
    """
    minimum = data.get("min_investment")
    maximum = data.get("max_investment")
    if minimum is not None and maximum is not None and maximum < minimum:
        raise ValidationError(
            "max_investment must be greater than or equal to min_investment.",
            field_name="max_investment",
        )


class ProductCreateSchema(Schema):
    """Validates ``POST /products``."""

    class Meta:
        unknown = RAISE

    name = fields.String(required=True, validate=_name)
    category = fields.Enum(ProductCategory, by_value=True, required=True)
    description = fields.String(required=False, allow_none=True)
    min_investment = fields.Decimal(
        required=True, as_string=True, validate=_positive_amount
    )
    max_investment = fields.Decimal(
        required=False, allow_none=True, as_string=True, validate=_positive_amount
    )
    duration_months = fields.Integer(required=True, validate=_positive_months)
    interest_rate = fields.Float(required=True, validate=_non_negative_rate)
    is_active = fields.Boolean(required=False)

    @validates_schema
    def _validate_window(self, data, **_kwargs):
        _check_amount_window(data)


class ProductUpdateSchema(Schema):
    """Validates ``PUT /products/{id}``. All fields optional (partial update)."""

    class Meta:
        unknown = RAISE

    name = fields.String(validate=_name)
    category = fields.Enum(ProductCategory, by_value=True)
    description = fields.String(allow_none=True)
    min_investment = fields.Decimal(as_string=True, validate=_positive_amount)
    max_investment = fields.Decimal(
        allow_none=True, as_string=True, validate=_positive_amount
    )
    duration_months = fields.Integer(validate=_positive_months)
    interest_rate = fields.Float(validate=_non_negative_rate)
    is_active = fields.Boolean()

    @validates_schema
    def _validate_window(self, data, **_kwargs):
        _check_amount_window(data)


class ProductResponseSchema(Schema):
    """List/summary representation of a product."""

    class Meta:
        unknown = EXCLUDE

    id = fields.Integer(dump_only=True)
    product_code = fields.String(dump_only=True)
    name = fields.String(dump_only=True)
    category = fields.Enum(ProductCategory, by_value=True, dump_only=True)
    description = fields.String(dump_only=True, allow_none=True)
    min_investment = fields.Decimal(as_string=True, dump_only=True)
    max_investment = fields.Decimal(as_string=True, dump_only=True, allow_none=True)
    duration_months = fields.Integer(dump_only=True)
    interest_rate = fields.Float(dump_only=True)
    is_active = fields.Boolean(dump_only=True)
    created_at = fields.DateTime(dump_only=True)
    updated_at = fields.DateTime(dump_only=True)


class ProductDetailSchema(ProductResponseSchema):
    """Detail representation.

    Adds how many proposals reference this product, which is what makes an
    admin's deactivate/delete decision an informed one.
    """

    proposal_count = fields.Method("_proposal_count", dump_only=True)

    def _proposal_count(self, product) -> int:
        return len(product.proposals)


# Singletons for reuse in routes.
product_create_schema = ProductCreateSchema()
product_update_schema = ProductUpdateSchema()
product_response_schema = ProductResponseSchema()
product_detail_schema = ProductDetailSchema()
products_response_schema = ProductResponseSchema(many=True)
