"""Shared paths, hyperparameters, and helpers for the training scripts.

Every script imports from here so that dataset locations and preprocessing
constants are defined exactly once. The normalization constants in particular
**must** stay in step with the inference code in ``app/ai/fraud`` — a model
trained under different normalization silently degrades when the detector runs
it (see :data:`IMAGENET_MEAN`).
"""

from __future__ import annotations

import os
import random
from pathlib import Path

# --- Layout -----------------------------------------------------------------
# ml_training/ lives at the repository root, next to app/.
PACKAGE_DIR = Path(__file__).resolve().parent
ROOT_DIR = PACKAGE_DIR.parent

# Authentic source scans you add by hand, one subfolder per document kind.
# This points at the folder that already holds the sample NIC/proposal images.
RAW_DIR = ROOT_DIR / "app" / "ai" / "training"

DATASETS_DIR = PACKAGE_DIR / "datasets"

# Fraud training set, generated by prepare_dataset.py.
FRAUD_DIR = DATASETS_DIR / "fraud"
GENUINE_DIR = FRAUD_DIR / "genuine"
TAMPERED_DIR = FRAUD_DIR / "tampered"
# Known-forgery exemplars you collect by hand; embedded into the Siamese
# reference bank rather than used as classifier training data.
REFERENCE_DIR = FRAUD_DIR / "reference"
MANIFEST_PATH = FRAUD_DIR / "manifest.csv"

# OCR ground truth: one JSON of expected field values per source image.
OCR_DIR = DATASETS_DIR / "ocr"
OCR_LABELS_DIR = OCR_DIR / "labels"
OCR_REPORT_PATH = OCR_DIR / "report.json"

# Field-box templates for ROI extraction (small JSON — safe to commit).
TEMPLATES_DIR = PACKAGE_DIR / "templates"

# Trained weight files consumed by the app via FRAUD_*_WEIGHTS.
MODELS_DIR = PACKAGE_DIR / "saved_models"
CNN_WEIGHTS_PATH = MODELS_DIR / "cnn_tamper.pt"
CNN_METRICS_PATH = MODELS_DIR / "cnn_tamper.metrics.json"
SIAMESE_WEIGHTS_PATH = MODELS_DIR / "siamese_embedder.pt"
SIAMESE_METRICS_PATH = MODELS_DIR / "siamese_embedder.metrics.json"
REFERENCE_BANK_PATH = MODELS_DIR / "reference_embeddings.pt"

DOC_KINDS = ("nic", "proposal")
IMAGE_EXTENSIONS = (".jpg", ".jpeg", ".png", ".webp", ".bmp", ".tif", ".tiff")

# --- Preprocessing ----------------------------------------------------------
# ResNet-18 input size and ImageNet normalization. These mirror
# app/ai/fraud/cnn_classifier.py::_run_inference and
# app/ai/fraud/siamese_detector.py::embed exactly. Change them in one place
# only if you change them in the other.
IMAGE_SIZE = 224
IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD = [0.229, 0.224, 0.225]

# --- Dataset synthesis ------------------------------------------------------
SEED = 42
# Variants generated per authentic source image, per class. The tampered count
# is spread across TAMPER_OPS so each forgery style is represented.
AUG_PER_IMAGE = 6
TAMPER_PER_IMAGE = 6
TAMPER_OPS = ("copymove", "splice", "textpatch", "requant")
# Fraction of *source images* (not variants) held out for validation.
VAL_FRACTION = 0.25

# --- CNN tamper classifier --------------------------------------------------
CNN_EPOCHS = 15
CNN_BATCH_SIZE = 16
CNN_LEARNING_RATE = 3e-4
CNN_WEIGHT_DECAY = 1e-4
CNN_PATIENCE = 5  # early-stop after this many epochs without val improvement

# --- Siamese embedder -------------------------------------------------------
SIAMESE_EPOCHS = 20
SIAMESE_BATCH_SIZE = 16
SIAMESE_LEARNING_RATE = 1e-4
SIAMESE_WEIGHT_DECAY = 1e-4
# Cosine-embedding margin: negatives are pushed below this similarity.
SIAMESE_MARGIN = 0.3
SIAMESE_PAIRS_PER_EPOCH = 512
SIAMESE_PATIENCE = 6


def ensure_dirs() -> None:
    """Create every generated directory (idempotent)."""
    for path in (
        GENUINE_DIR,
        TAMPERED_DIR,
        REFERENCE_DIR,
        OCR_LABELS_DIR,
        TEMPLATES_DIR,
        MODELS_DIR,
    ):
        path.mkdir(parents=True, exist_ok=True)


def set_seed(seed: int = SEED) -> None:
    """Seed Python, NumPy, and torch so a run is reproducible.

    torch is imported lazily: the labelling and calibration scripts need a seed
    but have no reason to pay for the torch import.
    """
    random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    try:
        import numpy as np

        np.random.seed(seed)
    except ImportError:  # pragma: no cover - numpy is a hard dependency
        pass
    try:
        import torch

        torch.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)
    except ImportError:  # pragma: no cover - torch only needed by trainers
        pass


def resolve_device(name: str = "auto"):
    """Return a ``torch.device``; ``"auto"`` prefers CUDA when available."""
    import torch

    if name == "auto":
        name = "cuda" if torch.cuda.is_available() else "cpu"
    return torch.device(name)


def iter_raw_images(doc_kinds=DOC_KINDS):
    """Yield ``(doc_kind, path)`` for every authentic scan under ``RAW_DIR``.

    Images sitting loose in ``RAW_DIR`` (not in a per-kind subfolder) are
    yielded with a doc kind of ``"unknown"`` so they are still usable for fraud
    training, where the document type does not matter.
    """
    if not RAW_DIR.is_dir():
        return

    for kind in doc_kinds:
        folder = RAW_DIR / kind
        if not folder.is_dir():
            continue
        for path in sorted(folder.iterdir()):
            if path.is_file() and path.suffix.lower() in IMAGE_EXTENSIONS:
                yield kind, path

    for path in sorted(RAW_DIR.iterdir()):
        if path.is_file() and path.suffix.lower() in IMAGE_EXTENSIONS:
            yield "unknown", path


def build_eval_transform():
    """Deterministic transform matching what the detectors do at inference."""
    from torchvision import transforms

    return transforms.Compose(
        [
            transforms.Resize((IMAGE_SIZE, IMAGE_SIZE)),
            transforms.ToTensor(),
            transforms.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
        ]
    )


def build_train_transform():
    """Eval transform plus mild jitter that does not fake tampering artifacts.

    Deliberately conservative: aggressive colour or geometric augmentation here
    would either mask the compression artifacts the classifier needs to see, or
    invent new ones. Content-level variation is baked into the dataset by
    ``prepare_dataset.py`` instead.
    """
    from torchvision import transforms

    return transforms.Compose(
        [
            transforms.Resize((IMAGE_SIZE, IMAGE_SIZE)),
            transforms.ColorJitter(brightness=0.1, contrast=0.1, saturation=0.05),
            transforms.ToTensor(),
            transforms.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
        ]
    )
