"""initial schema: 9 core tables

Revision ID: 187f9715fa10
Revises: 
Create Date: 2026-07-02 05:50:08.303845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '187f9715fa10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name='fk_branches_manager_id_users', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'head_office_staff', 'sales_rep', name='userrole'), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # Circular FK: branches.manager_id -> users.id. Added here via ALTER TABLE
    # because both tables must exist first (users also references branches).
    op.create_foreign_key(
        'fk_branches_manager_id_users', 'branches', 'users',
        ['manager_id'], ['id'],
    )

    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_code', sa.String(length=20), nullable=False),
    sa.Column('nic_number', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('assigned_rep_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'verified', 'flagged', name='customerstatus'), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_rep_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_code')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_nic_number'), ['nic_number'], unique=False)

    op.create_table('employee_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('target_customers', sa.Integer(), nullable=False),
    sa.Column('actual_customers', sa.Integer(), nullable=False),
    sa.Column('target_revenue', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('actual_revenue', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'month', 'year', name='uq_target_user_month_year')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('agreement_number', sa.String(length=30), nullable=False),
    sa.Column('investment_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('qr_code_token', sa.String(length=255), nullable=True),
    sa.Column('pdf_path', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'cancelled', name='agreementstatus'), nullable=False),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agreement_number'),
    sa.UniqueConstraint('qr_code_token')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.Enum('nic', 'bank_slip', 'bank_book', 'proposal_form', name='doctype'), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('extracted_fields', sa.JSON(), nullable=True),
    sa.Column('verification_status', sa.Enum('pending', 'verified', 'rejected', name='verificationstatus'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_sha256_hash'), ['sha256_hash'], unique=False)

    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('sales_rep_id', sa.Integer(), nullable=False),
    sa.Column('proposed_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('product_type', sa.String(length=100), nullable=True),
    sa.Column('workflow_status', sa.Enum('submitted', 'rep_review', 'ho_review', 'approved', 'rejected', name='proposalworkflowstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['sales_rep_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fraud_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('ela_score', sa.Float(), nullable=True),
    sa.Column('cnn_fraud_score', sa.Float(), nullable=True),
    sa.Column('siamese_similarity', sa.Float(), nullable=True),
    sa.Column('aggregate_score', sa.Float(), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('flag_reason', sa.String(length=250), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fraud_logs')
    op.drop_table('proposals')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_sha256_hash'))

    op.drop_table('documents')
    op.drop_table('agreements')
    op.drop_table('notifications')
    op.drop_table('employee_targets')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_nic_number'))

    op.drop_table('customers')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    # Drop the circular FK before dropping the tables it spans.
    op.drop_constraint('fk_branches_manager_id_users', 'branches', type_='foreignkey')
    op.drop_table('users')
    op.drop_table('branches')
    # ### end Alembic commands ###
