"""add is_deleted to customers

Revision ID: f325d629da73
Revises: 187f9715fa10
Create Date: 2026-07-21 06:05:44.571510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f325d629da73'
down_revision = '187f9715fa10'
branch_labels = None
depends_on = None


def upgrade():
    # Add with a server_default so existing rows backfill to False, then drop
    # the default so the application-level default (models.Customer) governs
    # new inserts.
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'is_deleted',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
        batch_op.create_index(batch_op.f('ix_customers_is_deleted'), ['is_deleted'], unique=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('is_deleted', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_is_deleted'))
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
